python main_isaac.py --headless='On' --object=box000
python main_isaac.py --headless='On' --object=box001
python main_isaac.py --headless='On' --object=box002
python main_isaac.py --headless='On' --object=box003
python main_isaac.py --headless='On' --object=box004
python main_isaac.py --headless='On' --object=box005
python main_isaac.py --headless='On' --object=box006
python main_isaac.py --headless='On' --object=box007
python main_isaac.py --headless='On' --object=box008
python main_isaac.py --headless='On' --object=box009
python main_isaac.py --headless='On' --object=box010
python main_isaac.py --headless='On' --object=box011
python main_isaac.py --headless='On' --object=box012
python main_isaac.py --headless='On' --object=box013
python main_isaac.py --headless='On' --object=box014
python main_isaac.py --headless='On' --object=box015
python main_isaac.py --headless='On' --object=box016
python main_isaac.py --headless='On' --object=box017
python main_isaac.py --headless='On' --object=box018
python main_isaac.py --headless='On' --object=box019
